{
 "title": "Kubernetes / Pod Metrics by kind",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kubernetes-service-endpoints\", namespace=~\"$namespace\"},created_by_kind)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=~\"$kind\", namespace=~\"$namespace\"}, created_by_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=~\"$kind\", created_by_name=~\"$resource\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod}}"
    }
   ]
  }
 ]
}