{
 "title": "Kubernetes / Pod Metrics",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\"}, pod)"
    }
   },
   {
    "name": "pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$pod\"}, pod_ip)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "label_values(kube_pod_status_phase{pod=\"$pod\"}, phase)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Pod IP Address", "type": "text", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 }, "options": { "content": "# $pod_ip" } },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=\"$pod\",phase=\"Running\",job=\"kubernetes-service-endpoints\"}==1 or (kube_pod_status_phase{pod=\"$pod\",phase=\"Pending\",job=\"kubernetes-service-endpoints\"}==1)+2 or (kube_pod_status_phase{pod=\"$pod\",phase=\"Succeeded\",job=\"kubernetes-service-endpoints\"}==1)+4 or (kube_pod_status_phase{pod=\"$pod\",phase=\"Failed\",job=\"kubernetes-service-endpoints\"}==1)+6 or (kube_pod_status_phase{pod=\"$pod\",phase=\"Unknown\",job=\"kubernetes-service-endpoints\"}==1)+8"
    }
   ]
  },
  {
   "title": "Pod Container",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_info{pod=\"$pod\",job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=\"$pod\",job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$pod$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$pod$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used by POD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$pod$\"})"
    }
   ]
  },
  {
   "title": "Total machine memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\"})"
    }
   ]
  },
  {
   "title": "Used by POD (cores)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$pod$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Used by all PODs on machine (cores)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"^$node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod memory working bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$pod$\"})"
    }
   ]
  },
  { "title": "Resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "Pod network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\", pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\", pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod}}"
    }
   ]
  }
 ]
}